"""OS-dispatched autoinstall: Ubuntu subiquity user-data + Fedora Kickstart dispatch.

The sole entry-point for callers is ``autoinstall_for_os``, which returns an
``AutoinstallPlan`` (files to stage + the Ventoy boot image + the template path) for each
supported OS family, or ``None`` when the family has no zero-touch support.

Family map
----------
* ``fedora`` → ``ks.cfg`` rendered by ``render_kscfg``, bound to the **netinst** ISO.
* ``debian`` → ``user-data`` + ``meta-data`` rendered by ``render_user_data``, bound to the
  **live** ISO (Ubuntu autoinstall needs no separate netinst).
"""

from __future__ import annotations

from dataclasses import dataclass

from devboost.core.osinfo import OsInfo
from devboost.media.config import IsoSpec, MediaConfig

# NoCloud requires meta-data to exist alongside user-data; an empty file is valid.
EMPTY_META_DATA: str = ""


# ---------------------------------------------------------------------------
# Fedora Kickstart renderer (source of truth; re-exported from stages for compat)
# ---------------------------------------------------------------------------


def render_kscfg(
    template: str, profiles: tuple[str, ...], *, offline: bool = False
) -> str:
    """Substitute the install command in a Kickstart template.

    Replaces the literal ``devboost install full`` placeholder with the actual
    profile list (e.g. ``devboost install cli shell``).  When *offline* is True
    ``--offline`` is appended.
    """
    install_cmd = "devboost install " + " ".join(profiles)
    if offline:
        install_cmd += " --offline"
    return template.replace("devboost install full", install_cmd)


# ---------------------------------------------------------------------------
# Ubuntu subiquity autoinstall renderer
# ---------------------------------------------------------------------------

_FIRSTBOOT_SVC_LINES: tuple[str, ...] = (
    "[Unit]",
    "Description=dev-boost first-boot provisioning",
    "After=network-online.target",
    "Wants=network-online.target",
    "ConditionPathExists=/opt/dev-boost/devboost",
    "",
    "[Service]",
    "Type=oneshot",
    "Environment=DEVBOOST_BOOTSTRAP_DIR=/opt/dev-boost",
    "Environment=DEVBOOST_SECRETS=/opt/dev-boost/secrets.age",
    "Environment=DEVBOOST_SECRETS_KEY=/opt/dev-boost/age-key.txt",
    # ExecStart is substituted per-call (profiles)
    "ExecStart=__EXECSTART__",
    "ExecStartPost=/bin/systemctl disable devboost-firstboot.service",
    "RemainAfterExit=yes",
    "",
    "[Install]",
    "WantedBy=multi-user.target",
)

# Destination path of the firstboot service unit in the target root.
_SVC_DEST = "/target/etc/systemd/system/devboost-firstboot.service"


def render_user_data(profiles: tuple[str, ...], *, arch: str) -> str:
    """Emit a subiquity ``#cloud-config`` autoinstall document.

    The identity block provisions a locked placeholder user ``devboost``; real
    credentials are applied during firstboot from the age bundle.

    Late-commands (run by the installer with target mounted at ``/target``):
      (a) Copy the dev-boost binary + age secrets bundle from the USB into
          ``/target/opt/dev-boost/`` (tries ``/cdrom/Bootstrap`` then the live
          medium fallback).
      (b) Write ``devboost-firstboot.service`` into the target's systemd unit dir.
      (c) Enable the firstboot service via ``curtin in-target``.
      (d) Ensure ``cloud-init`` is present in the target.
    """
    install_cmd = "/opt/dev-boost/devboost install " + " ".join(profiles)

    # Build the tee-heredoc block that writes the systemd unit.
    # Each line is prefixed with 6 spaces so YAML strips them correctly, leaving
    # a 0-indent shell script where the heredoc terminator sits at column 0.
    svc_lines = [
        line.replace("__EXECSTART__", install_cmd) for line in _FIRSTBOOT_SVC_LINES
    ]
    block_items: list[str] = (
        [
            "      tee " + _SVC_DEST + " > /dev/null << 'SVCEOF'",
        ]
        + [f"      {ln}" for ln in svc_lines]
        + ["      SVCEOF"]
    )
    write_svc_block = "\n".join(block_items)

    # (a) copy helpers — try /cdrom first (MBR boot), then live-medium path
    def _cp(src_file: str, dst_dir: str, extra: str = "") -> str:
        return (
            f"cp /cdrom/Bootstrap/{src_file} {dst_dir} 2>/dev/null"
            f" || cp /run/live/medium/Bootstrap/{src_file} {dst_dir} 2>/dev/null"
            + (f" || {extra}" if extra else " || true")
        )

    return (
        "#cloud-config\n"
        f"# Ubuntu subiquity autoinstall — generated by dev-boost (arch: {arch})\n"
        "# Provisional identity; real credentials are applied by"
        " devboost-firstboot.service.\n"
        "autoinstall:\n"
        "  version: 1\n"
        "  identity:\n"
        "    hostname: devboost-install\n"
        "    username: devboost\n"
        "    # Locked placeholder — firstboot secrets run sets the real password.\n"
        "    password: '*'\n"
        "  storage:\n"
        "    layout:\n"
        "      name: direct\n"
        "  packages:\n"
        "    - ubuntu-desktop-minimal\n"
        "  late-commands:\n"
        "    - mkdir -p /target/opt/dev-boost\n"
        "    - " + _cp("devboost", "/target/opt/dev-boost/") + "\n"
        "    - chmod +x /target/opt/dev-boost/devboost || true\n"
        "    - " + _cp("secrets.age", "/target/opt/dev-boost/") + "\n"
        "    - " + _cp("age-key.txt", "/target/opt/dev-boost/") + "\n"
        "    - mkdir -p /target/etc/systemd/system\n"
        "    - |\n"
        f"{write_svc_block}\n"
        "    - curtin in-target -- systemctl enable devboost-firstboot.service\n"
        "    - curtin in-target -- apt-get install -y cloud-init\n"
    )


# ---------------------------------------------------------------------------
# OS-dispatch plan
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class AutoinstallPlan:
    """Everything the staging layer needs to write an unattended-install config.

    ``files``          — Bootstrap/ file names → rendered content to stage.
    ``boot_iso``       — the ISO that Ventoy's ``auto_install`` block must point to.
    ``template_path``  — Ventoy ``template`` field value (e.g. ``/Bootstrap/user-data``).
    """

    files: dict[str, str]
    boot_iso: IsoSpec
    template_path: str


def autoinstall_for_os(
    os_info: OsInfo,
    cfg: MediaConfig,
    *,
    ks_template: str | None = None,
) -> AutoinstallPlan | None:
    """Return an ``AutoinstallPlan`` for *os_info.family*, or ``None`` if unsupported.

    Family dispatch:
    * ``fedora`` — ``ks.cfg`` + the *netinst* ISO (``cfg.autoinstall_iso``).
      Returns ``None`` when no netinst is configured.
    * ``debian`` — ``user-data`` + ``meta-data`` + the *live* ISO (``cfg.iso``).
    * anything else — ``None``.

    *ks_template* lets callers inject the raw Kickstart template text (useful for
    hermetic tests); when ``None`` the template is read from the packaged resource.
    """
    if os_info.family == "fedora":
        if cfg.autoinstall_iso is None:
            return None
        tmpl = ks_template
        if tmpl is None:
            from devboost.exec.resources import resource_path

            tmpl = resource_path("ventoy", "ks.cfg").read_text(encoding="utf-8")
        rendered_ks = render_kscfg(tmpl, cfg.profiles, offline=cfg.offline_mirror)
        return AutoinstallPlan(
            files={"ks.cfg": rendered_ks},
            boot_iso=cfg.autoinstall_iso,
            template_path="/Bootstrap/ks.cfg",
        )

    if os_info.family == "debian":
        return AutoinstallPlan(
            files={
                "user-data": render_user_data(cfg.profiles, arch=cfg.arch),
                "meta-data": EMPTY_META_DATA,
            },
            boot_iso=cfg.iso,
            template_path="/Bootstrap/user-data",
        )

    return None
