"""shell.bash loads env.sh + aliases.sh; fzf ≥ 0.48 integration with a fallback; the
shared aliases.sh is valid bash and zsh; ~/.bash_profile gives `bash -l` the shared env."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

from tests.dotfiles.test_zsh import shell_noise

from .conftest import DOT, FRAGMENTS, MakeBin

SHELL_BASH = FRAGMENTS / "shell.bash"
ALIASES = FRAGMENTS / "aliases.sh"
ZSH = shutil.which("zsh")


# The system bash when there is one (3.2 on macOS, which ~/.bash_profile must support);
# resolved here because the child PATH is minimal.
BASH = "/bin/bash" if Path("/bin/bash").exists() else shutil.which("bash") or "bash"


def _bash(home: Path, bin_dir: Path, script: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [BASH, "-c", f'source "$HOME/.config/devboost/shell.bash"; {script}'],
        env={"PATH": f"{bin_dir}:/usr/bin:/bin", "HOME": str(home)},
        capture_output=True, text=True,
    )


def test_fragments_parse() -> None:
    for f in (SHELL_BASH, ALIASES, DOT / "dot_bash_profile"):
        res = subprocess.run([BASH, "-n", str(f)], capture_output=True, text=True)
        assert res.returncode == 0, (f, res.stderr)
    if ZSH:
        res = subprocess.run([ZSH, "-n", str(ALIASES)], capture_output=True, text=True)
        assert res.returncode == 0, res.stderr


def test_shell_bash_loads_env_and_aliases(frag_home: Path, bin_dir: Path,
                                          make_bin: MakeBin) -> None:
    make_bin("ssh", "exit 0")
    make_bin("eza", "exit 0")
    res = _bash(frag_home, bin_dir, 'type -t dev; alias ls; printf "%s\\n" "$RIPGREP_CONFIG_PATH"')
    assert res.returncode == 0, res.stderr
    lines = res.stdout.splitlines()
    assert lines[0] == "function"
    assert "eza --group-directories-first" in lines[1]
    assert lines[2] == f"{frag_home}/.config/ripgrep/ripgreprc"


def test_modern_fzf_prints_its_own_bash_integration(frag_home: Path, bin_dir: Path,
                                                    make_bin: MakeBin) -> None:
    make_bin("fzf", '[ "$1" = "--bash" ] && { echo "FZF_BASH_INIT=new"; exit 0; }; exit 2')
    res = _bash(frag_home, bin_dir, 'printf "%s" "${FZF_BASH_INIT-<unset>}"')
    assert res.stdout == "new"


def test_old_fzf_falls_back_quietly(frag_home: Path, bin_dir: Path, make_bin: MakeBin) -> None:
    make_bin("fzf", 'echo "unknown option: $1" >&2; exit 2')  # fzf < 0.48 (Ubuntu 24.04)
    res = _bash(frag_home, bin_dir, 'printf "%s" "${FZF_BASH_INIT-<unset>}"')
    assert res.stdout == "<unset>"
    assert "unknown option" not in res.stderr
    assert "/usr/share/fzf/shell/key-bindings.bash" in SHELL_BASH.read_text(encoding="utf-8")


def test_aliases_never_shadow_zsh_path() -> None:
    # In zsh `path` is tied to $PATH — `local path=…` inside a function breaks every lookup.
    assert "local path=" not in ALIASES.read_text(encoding="utf-8")


@pytest.mark.skipif(ZSH is None, reason="zsh not installed")
def test_aliases_define_the_helpers_in_zsh(frag_home: Path, bin_dir: Path,
                                           make_bin: MakeBin) -> None:
    assert ZSH is not None
    make_bin("ssh", "exit 0")
    make_bin("claude", "exit 0")
    script = f'source "{frag_home}/.config/devboost/aliases.sh"; whence -w dev pw-workstation'
    res = subprocess.run(
        [ZSH, "-c", script],
        env={"PATH": f"{bin_dir}:/usr/bin:/bin", "HOME": str(frag_home)},
        capture_output=True, text=True,
    )
    assert res.stdout.splitlines() == ["dev: function", "pw-workstation: function"]


def test_shell_bash_sources_quietly_under_system_bash(frag_home: Path, bin_dir: Path) -> None:
    # macOS /bin/bash is 3.2: no globstar there. Sourcing must stay silent (M-R18).
    res = _bash(frag_home, bin_dir, "true")
    assert res.returncode == 0, res.stderr
    assert shell_noise(res.stderr) == ""


# ---------------------------------------------------------------------------
# ~/.bash_profile (macOS): `bash -l` launchers and interactive login bash
# ---------------------------------------------------------------------------


def _bash_login(home: Path, bin_dir: Path, script: str,
                *, interactive: bool = False) -> subprocess.CompletedProcess[str]:
    shutil.copy(DOT / "dot_bash_profile", home / ".bash_profile")
    flags = ["-l", "-i"] if interactive else ["-l"]
    return subprocess.run(
        [BASH, *flags, "-c", script],
        env={"PATH": f"{bin_dir}:/usr/bin:/bin", "HOME": str(home), "TERM": "dumb"},
        capture_output=True, text=True, timeout=30,
    )


def test_bash_profile_marker_and_local_file_note() -> None:
    text = (DOT / "dot_bash_profile").read_text(encoding="utf-8")
    assert "devboost — managed by chezmoi" in text
    assert "Do not edit this file manually" in text


def test_bash_login_gets_the_shared_env(frag_home: Path, bin_dir: Path) -> None:
    res = _bash_login(frag_home, bin_dir, 'printf "%s" "$RIPGREP_CONFIG_PATH"')
    assert res.stdout.endswith(f"{frag_home}/.config/ripgrep/ripgreprc"), res.stderr
    assert shell_noise(res.stderr) == ""


def test_bash_login_keeps_profile_then_env_then_local(frag_home: Path, bin_dir: Path) -> None:
    # ~/.profile (rustup, …) is read first, then env.sh, then ~/.bash_profile.local.
    (frag_home / ".profile").write_text("PROFILE_SAW_ENV=${RIPGREP_CONFIG_PATH:+1}\n",
                                        encoding="utf-8")
    (frag_home / ".bash_profile.local").write_text(
        "LOCAL_SAW=${PROFILE_SAW_ENV:-0}${RIPGREP_CONFIG_PATH:+1}\n", encoding="utf-8")
    res = _bash_login(frag_home, bin_dir, 'printf "%s" "$LOCAL_SAW"')
    assert res.stdout.endswith("01"), res.stderr  # .profile ran before env.sh; .local after
    assert shell_noise(res.stderr) == ""


def test_interactive_login_bash_loads_shell_bash(frag_home: Path, bin_dir: Path,
                                                 make_bin: MakeBin) -> None:
    make_bin("ssh", "exit 0")  # `dev` is defined only where ssh exists
    shutil.copy(DOT / "dot_bashrc", frag_home / ".bashrc")
    res = _bash_login(frag_home, bin_dir, "type -t dev", interactive=True)
    assert res.stdout.strip().splitlines()[-1] == "function", res.stderr


def test_non_interactive_login_bash_skips_bashrc(frag_home: Path, bin_dir: Path,
                                                make_bin: MakeBin) -> None:
    make_bin("ssh", "exit 0")
    shutil.copy(DOT / "dot_bashrc", frag_home / ".bashrc")
    res = _bash_login(frag_home, bin_dir, 'type -t dev || printf "none"')
    assert res.stdout.strip().splitlines()[-1] == "none", res.stderr
    assert shell_noise(res.stderr) == ""
