# ~/.config/devboost/env.sh — dev-boost's POSIX environment, shared by every shell
# (sourced by shell.bash and shell.zsh; on macOS also by ~/.bash_profile so `bash -lc`
# launchers see the same PATH). POSIX sh only: no bashisms.
#
# devboost — managed by chezmoi; edit dotfiles/dot_config/devboost/env.sh in the dev-boost
# repo. Do not edit this file manually.

# ---------------------------------------------------------------------------
# PATH — user bins first. Each directory is added once (a nested shell re-sourcing this
# file does not grow PATH) and only if it exists. Prepending puts the LAST one first, so
# the Android SDK goes on before the user bins and ~/.local/bin ends up at the front.
# ---------------------------------------------------------------------------
_devboost_path_prepend() {
  [ -d "$1" ] || return 0
  case ":${PATH}:" in
    *":$1:"*) ;;
    *) PATH="$1:${PATH}" ;;
  esac
}

# ---------------------------------------------------------------------------
# macOS — locale, XDG config dir, Android SDK location
# ---------------------------------------------------------------------------
if [ "$(uname -s)" = "Darwin" ]; then
  # macOS sends a bare LC_CTYPE=UTF-8 over ssh/mosh; Linux rejects it (mosh refuses to
  # start). A full locale name travels safely.
  export LANG="${LANG:-en_US.UTF-8}"
  if [ "${LC_CTYPE:-}" = "UTF-8" ]; then
    export LC_CTYPE=en_US.UTF-8
  fi
  # Without this, XDG-aware tools (lazygit, fresh, …) read ~/Library/Application Support
  # on macOS and never see the chezmoi-managed files in ~/.config.
  export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
  export ANDROID_HOME="${ANDROID_HOME:-${HOME}/Library/Android/sdk}"
fi
if [ -n "${ANDROID_HOME:-}" ]; then
  _devboost_path_prepend "${ANDROID_HOME}/platform-tools"
fi
# `dotnet tool install -g` (aspire, csharp-ls, csharpier) installs here; without this on
# PATH the tools install but are "not found" in an interactive shell.
_devboost_path_prepend "${HOME}/.dotnet/tools"
_devboost_path_prepend "${HOME}/.local/bin"
export PATH
unset -f _devboost_path_prepend

# ripgrep reads its config only from this variable.
export RIPGREP_CONFIG_PATH="${HOME}/.config/ripgrep/ripgreprc"

# ---------------------------------------------------------------------------
# Editors — fresh in every terminal; Zed as the *visual* editor only in a local GUI session.
# git has no core.editor, so it follows $VISUAL then $EDITOR (`zed --wait` returns when the
# tab is closed). Over SSH (even with a forwarded DISPLAY) Zed would open on the far screen.
# ---------------------------------------------------------------------------
export EDITOR=fresh
_devboost_gui=0
if [ -z "${SSH_CONNECTION:-}" ] && [ -z "${SSH_TTY:-}" ]; then
  if [ "$(uname -s)" = "Darwin" ]; then
    _devboost_gui=1
  elif [ -n "${DISPLAY:-}" ] || [ -n "${WAYLAND_DISPLAY:-}" ]; then
    _devboost_gui=1
  fi
fi
if [ "$_devboost_gui" = 1 ] && command -v zed >/dev/null 2>&1; then
  export VISUAL="zed --wait"
elif [ "${VISUAL:-}" = "zed --wait" ]; then
  # Inherited from a GUI parent (e.g. a tmux server started on the desktop) — useless here.
  unset VISUAL
fi
unset _devboost_gui

# ---------------------------------------------------------------------------
# Machine-local overrides (EDITOR, VISUAL, PATH, …) — last, so they win. local.sh is never
# managed by dev-boost: create it yourself; chezmoi neither ships nor touches it.
# ---------------------------------------------------------------------------
# shellcheck source=/dev/null
[ -r "${HOME}/.config/devboost/local.sh" ] && . "${HOME}/.config/devboost/local.sh"
true  # a missing local.sh must not make sourcing env.sh return non-zero
