# ~/.config/devboost/env.sh — dev-boost's POSIX environment, shared by every shell
# (sourced by shell.bash; the macOS shell.zsh sources it too). POSIX sh only: no bashisms.
#
# devboost — managed by chezmoi; edit dotfiles/dot_config/devboost/env.sh in the dev-boost
# repo. Do not edit this file manually.

# ---------------------------------------------------------------------------
# Editors — fresh in every terminal; Zed as the *visual* editor only in a local GUI session.
# git has no core.editor, so it follows $VISUAL then $EDITOR (`zed --wait` returns when the
# tab is closed). Over SSH (even with a forwarded DISPLAY) Zed would open on the far screen.
# ---------------------------------------------------------------------------
export EDITOR=fresh
_devboost_gui=0
if [ -z "${SSH_CONNECTION:-}" ] && [ -z "${SSH_TTY:-}" ]; then
  if [ "$(uname -s)" = "Darwin" ]; then
    _devboost_gui=1
  elif [ -n "${DISPLAY:-}" ] || [ -n "${WAYLAND_DISPLAY:-}" ]; then
    _devboost_gui=1
  fi
fi
if [ "$_devboost_gui" = 1 ] && command -v zed >/dev/null 2>&1; then
  export VISUAL="zed --wait"
elif [ "${VISUAL:-}" = "zed --wait" ]; then
  # Inherited from a GUI parent (e.g. a tmux server started on the desktop) — useless here.
  unset VISUAL
fi
unset _devboost_gui
