# ~/.config/devboost/shell.bash — dev-boost's portable interactive shell config.
#
# Kept SEPARATE from ~/.bashrc on purpose. On Fedora/Ubuntu dev-boost owns ~/.bashrc
# and it sources this file. On Omarchy the distro owns ~/.bashrc (it bootstraps
# OMARCHY_PATH and sources the Omarchy rc), so dev-boost appends a single guarded
# source line to the user-editable section instead of replacing the file. Same config
# either way, one copy of it, and no fight with `omarchy refresh`/`omarchy update`.
#
# The environment (PATH, EDITOR, …) is in env.sh and the dev/expose/pw-* helpers and
# aliases are in aliases.sh — both shared with zsh (shell.zsh on macOS). This file keeps
# what is bash-specific: shopt, bash-preexec and the bash tool initialisers.
#
# devboost — managed by chezmoi; edit dotfiles/dot_config/devboost/shell.bash in the
# dev-boost repo. Do not edit this file manually.

# ---------------------------------------------------------------------------
# Sensible defaults
# ---------------------------------------------------------------------------
HISTCONTROL=ignoredups:erasedups
HISTSIZE=100000
HISTFILESIZE=200000
shopt -s histappend
shopt -s checkwinsize
shopt -s globstar 2>/dev/null || true  # bash >= 4; macOS /bin/bash is 3.2

# ---------------------------------------------------------------------------
# POSIX environment shared with other shells (PATH, RIPGREP_CONFIG_PATH, EDITOR / VISUAL, …)
# ---------------------------------------------------------------------------
[[ -r "${HOME}/.config/devboost/env.sh" ]] && source "${HOME}/.config/devboost/env.sh"

# ---------------------------------------------------------------------------
# Shell tool initialisers — managed by dev-boost (single copy; no duplication)
# ---------------------------------------------------------------------------

# fzf — sourced FIRST so atuin (below) binds Ctrl-R last and owns it; fzf keeps
# Ctrl-T (files) and Alt-C (cd). Sourcing fzf after atuin steals Ctrl-R from atuin.
# fzf >= 0.48 prints its own integration (`fzf --bash`); older builds (Ubuntu 24.04 ships
# 0.44) reject the flag, so fall back to the distro's script paths.
if command -v fzf &>/dev/null && _devboost_fzf=$(fzf --bash 2>/dev/null); then
  eval "$_devboost_fzf"
else
  [ -f /usr/share/fzf/shell/key-bindings.bash ] && source /usr/share/fzf/shell/key-bindings.bash
  [ -f /usr/share/fzf/shell/completion.bash ]   && source /usr/share/fzf/shell/completion.bash
  [ -f /usr/share/doc/fzf/examples/key-bindings.bash ] && source /usr/share/doc/fzf/examples/key-bindings.bash
  [ -f "${HOME}/.fzf.bash" ] && source "${HOME}/.fzf.bash"
fi
unset _devboost_fzf

# starship — cross-shell prompt
command -v starship &>/dev/null && eval "$(starship init bash)"

# atuin — shell history search.
# On bash, atuin appends its hooks to precmd_functions/preexec_functions, which
# only exist (and only get invoked) if bash-preexec (or ble.sh) is loaded first.
# Without it, `atuin init bash` binds Ctrl-R but NEVER records commands — atuin
# reads as "not configured". bash-preexec is vendored via dotfiles (dot_bash-preexec.sh)
# so this works on Fedora and Ubuntu alike, not just where atuin's installer drops it.
if command -v atuin &>/dev/null; then
  [ -f "${HOME}/.bash-preexec.sh" ] && source "${HOME}/.bash-preexec.sh"
  eval "$(atuin init bash)"
fi

# zoxide — smarter cd
command -v zoxide &>/dev/null && eval "$(zoxide init bash)"

# direnv — per-directory env
command -v direnv &>/dev/null && eval "$(direnv hook bash)"

# mise — polyglot runtime/version manager; puts managed runtimes (node/python/…)
# on PATH for interactive shells. Without this, mise-installed tools aren't found.
command -v mise &>/dev/null && eval "$(mise activate bash)"

# ---------------------------------------------------------------------------
# Helpers (dev, expose, pw-*, …) and aliases — shared with zsh
# ---------------------------------------------------------------------------
[[ -r "${HOME}/.config/devboost/aliases.sh" ]] && source "${HOME}/.config/devboost/aliases.sh"
