# ~/.config/devboost/shell.zsh — dev-boost's interactive zsh config (macOS).
#
# Sourced by ~/.zshrc. The environment (env.sh) and the dev/expose/pw-* helpers and
# aliases (aliases.sh) are shared with bash (shell.bash); only zsh-specific parts live here.
#
# devboost — managed by chezmoi; edit dotfiles/dot_config/devboost/shell.zsh in the
# dev-boost repo. Do not edit this file manually.

[[ -r "${HOME}/.config/devboost/env.sh" ]] && source "${HOME}/.config/devboost/env.sh"

# ---------------------------------------------------------------------------
# History — shared live between sessions; atuin adds search on top.
# ---------------------------------------------------------------------------
HISTFILE="${HOME}/.zsh_history"
HISTSIZE=100000
SAVEHIST=100000
setopt share_history hist_ignore_all_dups hist_reduce_blanks extended_history
setopt interactive_comments

# ---------------------------------------------------------------------------
# Completion — Homebrew's site-functions (brew, gh, git, …) before compinit. The dump is
# cached per zsh version; -i skips insecure dirs instead of stopping to ask.
# ---------------------------------------------------------------------------
_devboost_brew="${HOMEBREW_PREFIX:-/opt/homebrew}"
[[ -d "${_devboost_brew}/share/zsh/site-functions" ]] &&
  fpath=("${_devboost_brew}/share/zsh/site-functions" $fpath)
_devboost_zcache="${XDG_CACHE_HOME:-${HOME}/.cache}/zsh"
[[ -d "$_devboost_zcache" ]] || mkdir -p "$_devboost_zcache"
autoload -Uz compinit
compinit -i -d "${_devboost_zcache}/zcompdump-${ZSH_VERSION}"

# ---------------------------------------------------------------------------
# Tool initialisers. fzf goes FIRST so atuin (below) binds Ctrl-R last and owns it;
# fzf keeps Ctrl-T (files) and Alt-C (cd).
# ---------------------------------------------------------------------------
# fzf and atuin are key bindings (zle widgets, bindkey), so they load only where the line
# editor can run: an interactive shell on a terminal. `zsh -i -c` with no tty (an editor
# capturing the env) reports zle "on" but cannot toggle it, and fzf's script then printed
# "can't change option: zle".
if [[ -o zle && -t 0 ]]; then
  # fzf >= 0.48 prints its own integration; an older fzf rejects --zsh: skip it quietly.
  (( $+commands[fzf] )) && _devboost_fzf=$(fzf --zsh 2>/dev/null) && eval "$_devboost_fzf"
fi
(( $+commands[mise] ))     && eval "$(mise activate zsh)"
(( $+commands[starship] )) && eval "$(starship init zsh)"
if [[ -o zle && -t 0 ]]; then
  (( $+commands[atuin] ))  && eval "$(atuin init zsh)"
fi
(( $+commands[zoxide] ))   && eval "$(zoxide init zsh)"
(( $+commands[direnv] ))   && eval "$(direnv hook zsh)"

# Helpers (dev, expose, pw-*, …) and aliases — shared with bash.
[[ -r "${HOME}/.config/devboost/aliases.sh" ]] && source "${HOME}/.config/devboost/aliases.sh"

# Open files for dev servers and file watchers. macos-limits raises the kernel cap to
# 524288; until then, take the current per-process maximum.
ulimit -n 524288 2>/dev/null ||
  ulimit -n "$(sysctl -n kern.maxfilesperproc 2>/dev/null || echo 10240)" 2>/dev/null

# ---------------------------------------------------------------------------
# Plugins LAST — they wrap every widget defined above. Syntax highlighting first, then
# autosuggestions (Homebrew formulae, installed by the zsh-plugins module).
# ---------------------------------------------------------------------------
[[ -r "${_devboost_brew}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]] &&
  source "${_devboost_brew}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
[[ -r "${_devboost_brew}/share/zsh-autosuggestions/zsh-autosuggestions.zsh" ]] &&
  source "${_devboost_brew}/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
unset _devboost_brew _devboost_zcache _devboost_fzf
